In [ ]:
# ---------------- BASICS ---------------------
import numpy as np

vector = np.array([1, 2, 3]) #1D array

matrix = np.array([
                  [4, 5, 6],
                  [7, 8, 9]
                  ]) #2D array

print(vector.shape)
print(matrix.shape)
#Check the dimensions (Vital for debugging shape errors later)

(3,)
(2, 3)


In [6]:
# -------------Indexing & Slicing -------------------
arr = np.arange(16).reshape(4, 4)
print("Original Matrix:\n", arr)

Original Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
print('Last Row:', arr[3])

Last Row: [12 13 14 15]


In [23]:
print('first 2 row:', arr[0:2])

first 2 row: [[0 1 2 3]
 [4 5 6 7]]


In [18]:
print ('Last Column:', arr[:, 3])

Last Column: [ 3  7 11 15]


In [21]:
print ('First 2 column:', arr[:, 0:2])

First 2 column: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [24]:
# Boolean Indexing (CRITICAL for Data Cleaning)
# This is how you filter data without 'for' loops.
mask = arr > 4
print(mask)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


# **Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes.**

In [3]:
import numpy as np

A = np.array([
              [1,1,1],
              [2,3,4],
              [5,6,7]
              ])
B = np.array([
             [1,2,3]
])

C = A + B

print ("Broadcasting Result", C)

Broadcasting Result [[ 2  3  4]
 [ 3  5  7]
 [ 6  8 10]]


In [5]:
import numpy as np

D = np.array([
              [1,1,1],
              [2,3,4],
              [5,6,7]
              ])
E = np.array([
             [1],
             [2],
             [3]
])

F = D + E

print ("Broadcasting Result", F)

Broadcasting Result [[ 2  2  2]
 [ 4  5  6]
 [ 8  9 10]]


# **Task:**

Generate a random 5x5 matrix with integers between 1 and 100.

Extract the sub-matrix of the middle 3x3 elements.

Replace all values greater than 50 with 0.

In [9]:
import numpy as np
data = np.random.randint(1, 101, size=(5, 5))
print (data)

[[93 35  3 45 28]
 [58 91  7 25 67]
 [49 68  2 33 67]
 [89 86 25 91 61]
 [91 44 10 92 70]]


In [10]:
middle = data[1:4, 1:4]
print(middle)

[[91  7 25]
 [68  2 33]
 [86 25 91]]


In [12]:
data[data > 50] = 0
print (data)


[[ 0 35  3 45 28]
 [ 0  0  7 25  0]
 [49  0  2 33  0]
 [ 0  0 25  0  0]
 [ 0 44 10  0  0]]


# **Task 1: **
The "Normalizer" (Standardization):

In Machine Learning, your data will have different scales (e.g., Age: 0-100, Salary: 10000-100000). You must scale them to a standard range (Mean = 0, Std Dev = 1) or your model will crash.

**The Drill:**

Create a (5, 3) matrix representing 5 samples with 3 features each (Random integers 1-100).Calculate the mean and standard deviation of each column (feature).Subtract the mean from each element and divide by the standard deviation. (This is the formula: $Z = \frac{X - \mu}{\sigma}$)Hint: Use axis=0 for column-wise operations.

In [4]:
import numpy as np
X = np.random.randint(1, 100, (5,3))
print(X)

mean = X.mean(axis=0)
std = X.std(axis=0)
print(mean)
print(std)

[[ 3 90 41]
 [18  7 76]
 [42 86 13]
 [29 11 95]
 [26 70 69]]
[23.6 52.8 58.8]
[12.87788803 36.40549409 28.72211691]


In [5]:
mean = X.mean(axis=0)
std = X.std(axis=0)
print(mean)
print(std)

[23.6 52.8 58.8]
[12.87788803 36.40549409 28.72211691]


In [6]:
X_normalized = (X - mean) / std
print(X_normalized)

[[-1.59964118  1.02182379 -0.61973148]
 [-0.43485391 -1.25805187  0.59884165]
 [ 1.42880571  0.91195027 -1.59458999]
 [ 0.41932342 -1.14817835  1.26035278]
 [ 0.18636596  0.47245616  0.35512703]]


In [7]:
print(X_normalized.mean(axis=0))
print(X_normalized.std(axis=0))

[-6.66133815e-17  5.55111512e-17  1.33226763e-16]
[1. 1. 1.]
